name: Go

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

#    - name: Init
#      run: go mod init milkyway

    - name: Tidy
      run: go mod tidy

    - name: Build
      run: go build -v ./...

#    - name: Test
#      run: go test -v ./...
